version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    environment:
      QDRANT__SERVICE__GRPC_PORT: "6334"
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'ai_dev'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '13306:3306'
    volumes:
      - ./my-db:/var/lib/mysql
