version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/DOCKERFILE
    restart:  always
    volumes:
      - ./app:/src
    command: npm run start
    ports:
      - "8080:3000"
